Retry all kubectl commands

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -13,19 +13,46 @@ fi
 ((timeout=BUILDKITE_TIMEOUT*60))
 export BUILDKITE_TIMEOUT
 
+readonly job_apply_loop_interval_seconds="${K8S_BUILDKITE_PLUGIN_JOB_APPLY_LOOP_INTERVAL:-5}"
+readonly job_apply_loop_timeout_seconds="${K8S_BUILDKITE_PLUGIN_JOB_APPLY_LOOP_TIMEOUT:-120}"
 readonly log_loop_interval_seconds="${K8S_BUILDKITE_PLUGIN_LOG_LOOP_INTERVAL:-3}"
+readonly cleanup_loop_interval_seconds="${K8S_BUILDKITE_PLUGIN_CLEANUP_LOOP_INTERVAL:-5}"
+readonly cleanup_loop_timeout_seconds="${K8S_BUILDKITE_PLUGIN_CLEANUP_LOOP_INTERVAL:-60}"
+
+readonly job_json="$(mktemp)"
 readonly job_log_complete_marker_file="$(mktemp)"
 
 function cleanup {
   # Delete all jobs older than a day
-  kubectl delete job "$(kubectl get job -l buildkite/plugin=k8s | awk 'match($4,/[0-9]+d/) {print $1}')" 2>/dev/null || true
-  rm -f "$job_log_complete_marker_file"
+  local -r cleanup_start_time="$SECONDS"
+  local cleanup_old_jobs_exit_code=""
+
+  while [[ "$((SECONDS - cleanup_start_time))" -lt "$cleanup_loop_timeout_seconds" ]]
+  do
+    set +e
+    local old_jobs="$(kubectl get job -l buildkite/plugin=k8s | awk 'match($4,/[0-9]+d/) {print $1}')"
+    if [[ -n "$old_jobs" ]]; then
+      kubectl delete job "$old_jobs"
+    fi
+    cleanup_old_jobs_exit_code="$?"
+    set -e
+
+    if [[ "$cleanup_old_jobs_exit_code" == "0" ]]; then
+      break
+    else
+      echo "Attempt to cleanup old jobs failed, exit code '$cleanup_old_jobs_exit_code'"
+      sleep "$cleanup_loop_interval_seconds"
+    fi
+  done
+
+  echo "Cleanup old jobs exit code '$cleanup_old_jobs_exit_code'"
+  rm -f "$job_json" "$job_log_complete_marker_file"
 }
 trap cleanup EXIT
 
 function tail_logs {
   local log_snapshot=""
-  # Once logs are not empty we should start attempting to stream them.
+  # Once logs are not empty we start attempting to stream them.
   # Keep looping otherwise since empty output means that there is no useful log to display so we're not losing information by looping.
   while true;
   do
@@ -42,7 +69,10 @@ function tail_logs {
   #   1) It can fail due to pod not being initialized yet: "Error from server (BadRequest): container "step" in pod "somepod" is waiting to start: PodInitializing"
   #   2) It can fail mid-streaming, in this case we unfortunately will display logs multiple times (partially).
   #   3) It can hang not providing any result, that's why we check not only exit code but also contents in the loop above.
-  while ! kubectl logs --follow "job/${job_name}" 2>/dev/null; do sleep 0.2; done
+  while ! kubectl logs --follow "job/${job_name}" 2>/dev/null;
+  do
+    sleep "$log_loop_interval_seconds"
+  done
 
   echo "0" > "$job_log_complete_marker_file"
 }
@@ -57,7 +87,26 @@ jsonnet \
   --tla-code "agentEnv=$(jq -c -n env)" \
   --tla-code patchFunc \
   "${basedir}/lib/job.jsonnet" \
-  | kubectl apply -f -
+  > "$job_json"
+
+readonly job_apply_start_time="$SECONDS"
+job_apply_exit_code=""
+
+while [[ "$((SECONDS - job_apply_start_time))" -lt "$job_apply_loop_timeout_seconds" ]]
+do
+  set +e
+  kubectl apply -f "$job_json"
+  job_apply_exit_code="$?"
+  set -e
+
+  if [[ "$job_apply_exit_code" == "0" ]]; then
+    break
+  else
+    echo "Attempt apply the job failed, exit code '$job_apply_exit_code'"
+    sleep "$job_apply_loop_interval_seconds"
+  fi
+done
+echo "Apply job exit code '$job_apply_exit_code'"
 
 echo "Timeout: ${timeout}s"
 
@@ -65,11 +114,13 @@ echo "+++ :kubernetes: Running image: ${BUILDKITE_PLUGIN_K8S_IMAGE}"
 
 tail_logs &
 
-sleeper=2
+readonly sleeper="${K8S_BUILDKITE_PLUGIN_SLEEPER_LOOP_INTERVAL:-5}"
 counter=${timeout}
 jobstatus=""
 while [[ -z "$jobstatus" ]] ; do
+  set +e
   jobstatus=$(kubectl get job "${job_name}" -o 'jsonpath={.status.conditions[].type}')
+  set -e
   sleep $sleeper
   if [[ $timeout -gt 0 ]]; then
     (( counter -= sleeper )) || jobstatus="timeout"
