Handle pod never being created (#33)
* Handle pod never being created

When we have limited resources in our cluster we see this logging:

```
Error from server (NotFound): pods "ios-714486-aulol72k-brp2m" not found
Error from server (NotFound): pods "ios-714486-aulol72k-brp2m" not found
Error from server (NotFound): pods "ios-714486-aulol72k-brp2m" not found
Error from server (NotFound): pods "ios-714486-aulol72k-brp2m" not found
Error from server (NotFound): pods "ios-714486-aulol72k-brp2m" not found
Error from server (NotFound): pods "ios-714486-aulol72k-brp2m" not found
```

Which eventually leads to a buildkite timeout. I believe this is caused
by the loop below never getting a valid status because the pod failed to
be created in the first place.

* Move into init container block

* Print remaining error

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -194,15 +194,24 @@ else
   while true
   do
     set +e
-    pod_json=$(kubectl get pod "$pod_name" -o json)
-    init_container_status="$(echo "$pod_json" | jq ".status.initContainerStatuses[0].state.terminated.exitCode")"
-    if [[ -n "$init_container_status" && "$init_container_status" != "0" ]]; then
-      echo "Warning: init container failed with exit code $init_container_status, this usually indicates plugin misconfiguration or infrastructure failure"
-      status="$init_container_status"
+    pod_json=$(kubectl get pod "$pod_name" -o json 2>&1)
+    get_pod_status=$?
+    if [[ "$get_pod_status" -eq 0 ]]; then
+      init_container_status="$(echo "$pod_json" | jq ".status.initContainerStatuses[0].state.terminated.exitCode")"
+      if [[ -n "$init_container_status" && "$init_container_status" != "0" ]]; then
+        echo "Warning: init container failed with exit code $init_container_status, this usually indicates plugin misconfiguration or infrastructure failure"
+        status="$init_container_status"
+      else
+        status="$(echo "$pod_json" | jq ".status.containerStatuses[0].state.terminated.exitCode")"
+      fi
+    elif [[ "$pod_json" == *NotFound* ]]; then
+      echo "Warning: pod not found"
+      status="42"
     else
-      status="$(echo "$pod_json" | jq ".status.containerStatuses[0].state.terminated.exitCode")"
+      echo "$pod_json" >&2
     fi
     set -e
+
     if [[ -n "$status" ]]; then
       break
     else
