Get job status when pod doesn't exist (#36)
* Get job status when pod doesn't exist

In the case a pod is scheduled on a node, then evicted, you can end up
in a state where you search for the pod forever when the job was already
know to have failed:

```
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
```

This checks the job status and exits if it has failed in that case

* Update hooks/command

Co-authored-by: Ifeanyi Ubah <ify1992@yahoo.com>

* Only check job status on NotFound error

* Redirect stderr

Co-authored-by: Ifeanyi Ubah <ify1992@yahoo.com>

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -134,9 +134,21 @@ echo "--- :kubernetes: Running image: ${BUILDKITE_PLUGIN_K8S_IMAGE}"
 counter="$timeout"
 while true
 do
+  exit_status=0
   set +e
-  pod_name=$(kubectl get pod -l "job-name=$job_name" --output=jsonpath="{.items[*].metadata.name}")
+  pod_name=$(kubectl get pod -l "job-name=$job_name" --output=jsonpath="{.items[*].metadata.name}" 2>&1)
+  exit_status=$?
   set -e
+
+  if [[ $exit_status -ne 0 && "$pod_name" == *NotFound* ]]; then
+      set +e
+      jobstatus=$(kubectl get job "$job_name" -o 'jsonpath={.status.conditions[].type}')
+      set -e
+      if [[ "$jobstatus" == "Failed" ]]; then
+        echo "Warning: exiting because no pod was found and job status was Failed"
+        exit 42
+      fi
+  fi
 
   if [[ -n "$pod_name" ]]; then
     break
