Get job status when pod doesn't exist
In the case a pod is scheduled on a node, then evicted, you can end up
in a state where you search for the pod forever when the job was already
know to have failed:

```
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
Error from server (NotFound): pods "ios-714750-zjyo7cyw-gsnzh" not found
```

This checks the job status and exits if it has failed in that case

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -136,6 +136,14 @@ do
   if [[ -n "$pod_name" ]]; then
     break
   else
+    set +e
+    jobstatus=$(kubectl get job "$job_name" -o 'jsonpath={.status.conditions[].type}')
+    set -e
+    if [[ "$jobstatus" == "Failed" ]]; then
+      echo "Warning: job failed to create pod"
+      exit 42
+    fi
+
     sleep "$job_status_retry_interval_sec"
     if [[ $timeout -gt 0 ]]; then
       (( counter -= job_status_retry_interval_sec ))
