Only check job status on NotFound error

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -126,22 +126,28 @@ echo "Timeout: ${timeout}s"
 
 echo "--- :kubernetes: Running image: ${BUILDKITE_PLUGIN_K8S_IMAGE}"
 
+error_file=$(mktemp)
 counter="$timeout"
 while true
 do
+  echo -n > "$error_file"
   set +e
-  pod_name=$(kubectl get pod -l "job-name=$job_name" --output=jsonpath="{.items[*].metadata.name}")
+  pod_name=$(kubectl get pod -l "job-name=$job_name" --output=jsonpath="{.items[*].metadata.name}" 2>"$error_file")
   set -e
 
   if [[ -n "$pod_name" ]]; then
     break
   else
-    set +e
-    jobstatus=$(kubectl get job "$job_name" -o 'jsonpath={.status.conditions[].type}')
-    set -e
-    if [[ "$jobstatus" == "Failed" ]]; then
-      echo "Warning: exiting because no pod was found and job status was Failed"
-      exit 42
+    if grep -q NotFound "$error_file"; then
+      set +e
+      jobstatus=$(kubectl get job "$job_name" -o 'jsonpath={.status.conditions[].type}')
+      set -e
+      if [[ "$jobstatus" == "Failed" ]]; then
+        echo "Warning: exiting because no pod was found and job status was Failed"
+        exit 42
+      fi
+    elif [[ -s "$error_file" ]]; then
+      cat "$error_file" >&2
     fi
 
     sleep "$job_status_retry_interval_sec"
